/* =====================================================================
 * levels.js — Les appareils à réparer
 * Chaque niveau décrit : les composants (position, paramètres, état initial),
 * les fils (bornes reliées, avec points de passage pour le dessin), les
 * scénarios de panne possibles (un est tiré au sort), et les tests
 * fonctionnels qui valident la réparation.
 * Une borne s'écrit "idComposant.pin". Un fil est ["c1.p", [x,y]..., "c2.q"].
 * ===================================================================== */

/* Catalogue des pièces de rechange (prix en €) */
const STOCK = [
  { type: 'lampe', label: 'Ampoule E27 60 W / 230 V', params: { P: 60, V: 230 }, price: 3 },
  { type: 'lampe', label: 'Ampoule E27 40 W / 230 V', params: { P: 40, V: 230 }, price: 2.5 },
  { type: 'led', label: 'LED blanche 5 mm', params: { R: 100 }, price: 0.3 },
  { type: 'voyant', label: 'Voyant néon 230 V', params: { R: 220000 }, price: 2 },
  { type: 'interrupteur', label: 'Interrupteur unipolaire 10 A', params: {}, price: 4 },
  { type: 'porte', label: 'Sécurité de porte', params: {}, price: 12 },
  { type: 'commutateur', label: 'Commutateur 3 positions', params: {}, price: 9 },
  { type: 'fusible', label: 'Fusible verre 2 A', params: { I: 2 }, price: 1 },
  { type: 'fusible', label: 'Fusible verre 5 A', params: { I: 5 }, price: 1 },
  { type: 'fusible', label: 'Fusible verre 10 A', params: { I: 10 }, price: 1 },
  { type: 'fusible', label: 'Fusible verre 16 A', params: { I: 16 }, price: 1 },
  { type: 'thermofusible', label: 'Fusible thermique 150 °C', params: { T: 150 }, price: 3 },
  { type: 'thermofusible', label: 'Fusible thermique 170 °C', params: { T: 170 }, price: 3 },
  { type: 'thermostat', label: 'Thermostat bilame 60 °C', params: { T: 60 }, price: 8 },
  { type: 'thermostat', label: 'Thermostat bilame 90 °C', params: { T: 90 }, price: 8 },
  { type: 'thermostat', label: 'Thermostat bilame 100 °C', params: { T: 100 }, price: 8 },
  { type: 'thermostat', label: 'Thermostat bilame 200 °C', params: { T: 200 }, price: 8 },
  { type: 'resistance', label: 'Résistance 400 W / 230 V', params: { P: 400, V: 230 }, price: 12 },
  { type: 'resistance', label: 'Résistance 1200 W / 230 V', params: { P: 1200, V: 230 }, price: 15 },
  { type: 'resistance', label: 'Résistance 2000 W / 230 V', params: { P: 2000, V: 230 }, price: 18 },
  { type: 'resistor', label: 'Résistance 100 Ω 1/4 W', params: { R: 100 }, price: 0.2 },
  { type: 'resistor', label: 'Résistance 1 kΩ 1/4 W', params: { R: 1000 }, price: 0.2 },
  { type: 'moteur', label: 'Moteur universel 40 W', params: { P: 40, V: 230 }, price: 18 },
  { type: 'moteur', label: 'Pompe de vidange 30 W', params: { P: 30, V: 230 }, price: 20 },
  { type: 'moteur', label: 'Moteur tambour 400 W', params: { P: 400, V: 230 }, price: 60 },
  { type: 'moteur_async', label: 'Moteur asynchrone 50 W', params: { P: 50, V: 230 }, price: 25 },
  { type: 'condensateur', label: 'Condensateur 1 µF 450 V', params: { C: 1 }, price: 4 },
  { type: 'condensateur', label: 'Condensateur 2 µF 450 V', params: { C: 2 }, price: 4.5 },
  { type: 'condensateur', label: 'Condensateur 4 µF 450 V', params: { C: 4 }, price: 5 },
  { type: 'cordon', label: 'Cordon 2 × 0,75 mm² avec fiche', params: {}, price: 6 },
  { type: 'connexion', label: 'Cosse / connecteur neuf', params: {}, price: 0.5 },
  { type: 'pile', label: 'Pile plate 4,5 V', params: { V: 4.5 }, price: 2 },
  { type: 'electrovanne', label: 'Électrovanne 230 V', params: { R: 4000 }, price: 14 },
];

const LEVELS = [
  /* ================================================================ */
  {
    id: 'lampe',
    name: 'Lampe de chevet',
    icon: '🛋️',
    difficulty: 1,
    intro: "Le plus simple des circuits : une prise, un cordon, un interrupteur et une ampoule, tous en série. Idéal pour apprendre à mesurer.",
    ground: 'prise.N',
    ac: true,
    comps: [
      { id: 'prise', type: 'prise', x: 70, y: 230, params: { V: 230 }, state: { plugged: false } },
      { id: 'cordon', type: 'cordon', x: 200, y: 230, label: 'Cordon' },
      { id: 'sw', type: 'interrupteur', x: 400, y: 120, label: 'Interrupteur', state: { on: false } },
      { id: 'lampe', type: 'lampe', x: 640, y: 230, rot: 90, label: 'Ampoule', params: { P: 60, V: 230 } },
    ],
    wires: [
      ['prise.L', 'cordon.L1'], ['prise.N', 'cordon.N1'],
      ['cordon.L2', [240, 120], 'sw.a'],
      ['sw.b', [640, 120], 'lampe.a'],
      ['lampe.b', [640, 340], [240, 340], 'cordon.N2'],
    ],
    scenarios: [
      { faults: { lampe: 'grillee' }, symptom: "« Ma lampe ne s'allume plus. »", lesson: "L'ampoule était grillée : à l'ohmmètre son filament donnait ∞ au lieu d'environ 880 Ω. Sous tension, on lisait pourtant 230 V à ses bornes : la tension arrivait, mais elle ne pouvait pas être « consommée »." },
      { faults: { sw: 'ouvert' }, symptom: "« Ma lampe ne s'allume plus, j'ai déjà changé l'ampoule. »", lesson: "L'interrupteur ne fermait plus : en position ON il restait ∞ à l'ohmmètre, et sous tension on mesurait 230 V à ses bornes (toute la tension se retrouve aux bornes de l'élément ouvert)." },
      { faults: { cordon: 'coupeL' }, symptom: "« La lampe ne marche plus depuis que le chien a tiré sur le fil. »", lesson: "Le conducteur de phase du cordon était coupé. Test de continuité de chaque conducteur : l'un des deux était ∞." },
      { faults: { cordon: 'coupeN' }, symptom: "« La lampe s'est éteinte quand j'ai déplacé le meuble. »", lesson: "Le neutre du cordon était coupé. Attention : la phase arrivait bien jusqu'à l'ampoule (230 V entre L et le neutre de la prise), mais le circuit n'était pas refermé." },
      { faults: { sw: 'colle' }, symptom: "« Impossible d'éteindre la lampe, l'interrupteur ne fait plus rien. »", lesson: "Les contacts de l'interrupteur étaient soudés : il laissait passer le courant même en position OFF (0 Ω dans les deux positions)." },
    ],
    tutorial: [
      { text: "Branchez la prise murale et mettez l'interrupteur sur ON (sélectionnez-les puis « Actionner »). Observez le constat : l'ampoule reste éteinte.", done: (S) => S.comps.prise.state.plugged && S.comps.sw.state.on },
      { text: "Multimètre en <b>V~</b>. Posez la pointe rouge sur la borne L de la prise et la noire sur N : vous devez lire 230 V. Le courant arrive bien.", done: (S) => S.history.some((m) => m.mode === 'V~' && m.powered && m.pair('prise.L', 'prise.N')) },
      { text: "Toujours en V~, mesurez aux <b>bornes de l'ampoule</b>. 230 V = la tension arrive jusqu'à elle (donc elle est coupée… ou tout va bien avant elle). 0 V = le circuit est ouvert ailleurs : remontez vers la prise en mesurant chaque élément.", done: (S) => S.history.some((m) => m.mode === 'V~' && m.powered && m.pair('lampe.a', 'lampe.b')) },
      { text: "<b>Débranchez</b> la prise : on ne mesure jamais une résistance sous tension.", done: (S) => !S.comps.prise.state.plugged && S.history.some((m) => m.mode === 'V~' && m.pair('lampe.a', 'lampe.b')) },
      { text: "Multimètre en <b>Ω</b>. Ampoule : ≈ 880 Ω si elle est bonne, ∞ si elle est grillée. Interrupteur en ON : 0 Ω attendu. Cordon : 0 Ω sur chaque conducteur (L1↔L2, N1↔N2).", done: (S) => S.history.some((m) => m.mode === 'Ω' && !m.powered) },
      { text: "Vous avez trouvé la pièce à ∞ (ou à 0 Ω alors qu'elle devrait couper) ? Sélectionnez-la → <b>Remplacer</b>, puis lancez le <b>✅ Test final</b>.", done: (S) => S.finished },
    ],
    tests: [
      { name: 'Interrupteur ON → la lampe éclaire', controls: { sw: { on: true } }, expect: { lampe: 'on' } },
      { name: "Interrupteur OFF → la lampe s'éteint", controls: { sw: { on: false } }, expect: { lampe: 'off' } },
    ],
  },

  /* ================================================================ */
  {
    id: 'grillepain',
    name: 'Grille-pain',
    icon: '🍞',
    difficulty: 2,
    intro: "Deux résistances chauffantes en parallèle (une par face), un fusible, un levier de mise en marche et un thermostat qui régule la chauffe.",
    ground: 'prise.N',
    ac: true,
    fuse: { id: 'fusible', I: 5 },
    comps: [
      { id: 'prise', type: 'prise', x: 70, y: 230, params: { V: 230 }, state: { plugged: false } },
      { id: 'cordon', type: 'cordon', x: 200, y: 230, label: 'Cordon' },
      { id: 'fusible', type: 'fusible', x: 330, y: 120, label: 'Fusible', params: { I: 5 } },
      { id: 'sw', type: 'interrupteur', x: 470, y: 120, label: 'Levier', state: { on: false } },
      { id: 'thermostat', type: 'thermostat', x: 610, y: 120, label: 'Thermostat', params: { T: 200, sensor: 'res1' } },
      { id: 'res1', type: 'resistance', x: 700, y: 230, rot: 90, label: 'Résistance face A', params: { P: 400, V: 230 } },
      { id: 'res2', type: 'resistance', x: 780, y: 230, rot: 90, label: 'Résistance face B', params: { P: 400, V: 230 } },
    ],
    wires: [
      ['prise.L', 'cordon.L1'], ['prise.N', 'cordon.N1'],
      ['cordon.L2', [240, 120], 'fusible.a'],
      ['fusible.b', 'sw.a'], ['sw.b', 'thermostat.a'],
      ['thermostat.b', [700, 120], 'res1.a'],
      ['thermostat.b', [780, 120], 'res2.a'],
      ['res1.b', [700, 340], [240, 340], 'cordon.N2'],
      ['res2.b', [780, 340], [240, 340], 'cordon.N2'],
    ],
    scenarios: [
      { faults: { res2: 'coupee' }, symptom: "« Mon grille-pain ne grille le pain que d'un seul côté. »", lesson: "Une des deux résistances (en parallèle) était coupée. L'autre fonctionnait normalement : c'est le propre du montage en parallèle, chaque branche est indépendante." },
      { faults: { fusible: 'grille' }, symptom: "« Plus rien ne se passe quand je baisse le levier. »", lesson: "Le fusible était grillé (∞ à l'ohmmètre). Il avait vieilli. Il fallait le remplacer par le même calibre : 5 A." },
      { faults: { sw: 'ouvert' }, symptom: "« Le levier descend mais ça ne chauffe pas. »", lesson: "Le contact du levier était usé : sous tension on trouvait 230 V avant lui et 0 V après lui." },
      { faults: { res1: 'cc', fusible: 'grille' }, symptom: "« Il y a eu un flash, une odeur de brûlé, et plus rien. »", lesson: "Double panne : la résistance A était en court-circuit (résistance bien trop faible : V²/P prévoit 132 Ω) et elle a fait griller le fusible. Remplacer seulement le fusible l'aurait fait regriller aussitôt : il faut toujours chercher la CAUSE." },
    ],
    tests: [
      { name: 'Levier ON → les deux faces chauffent, le thermostat régule', controls: { sw: { on: true } }, expect: { res1: 'on', res2: 'on', thermostat: 'regule' } },
      { name: 'Levier OFF → rien ne chauffe', controls: { sw: { on: false } }, expect: { res1: 'off', res2: 'off' } },
    ],
  },

  /* ================================================================ */
  {
    id: 'bouilloire',
    name: 'Bouilloire',
    icon: '🫖',
    difficulty: 2,
    intro: "Une grosse résistance de 2000 W, un thermostat qui coupe à l'ébullition, un fusible thermique de sécurité et un voyant en parallèle.",
    ground: 'prise.N',
    ac: true,
    comps: [
      { id: 'prise', type: 'prise', x: 70, y: 230, params: { V: 230 }, state: { plugged: false } },
      { id: 'cordon', type: 'cordon', x: 200, y: 230, label: 'Cordon' },
      { id: 'thermofusible', type: 'thermofusible', x: 330, y: 120, label: 'Fusible thermique', params: { T: 170, sensor: 'res' } },
      { id: 'sw', type: 'interrupteur', x: 470, y: 120, label: 'Interrupteur', state: { on: false } },
      { id: 'thermostat', type: 'thermostat', x: 610, y: 120, label: 'Thermostat', params: { T: 100, sensor: 'res' } },
      { id: 'res', type: 'resistance', x: 700, y: 230, rot: 90, label: 'Résistance', params: { P: 2000, V: 230 } },
      { id: 'voyant', type: 'voyant', x: 780, y: 230, rot: 90, label: 'Voyant', params: { R: 220000 } },
    ],
    wires: [
      ['prise.L', 'cordon.L1'], ['prise.N', 'cordon.N1'],
      ['cordon.L2', [240, 120], 'thermofusible.a'],
      ['thermofusible.b', 'sw.a'], ['sw.b', 'thermostat.a'],
      ['thermostat.b', [700, 120], 'res.a'],
      ['thermostat.b', [780, 120], 'voyant.a'],
      ['res.b', [700, 340], [240, 340], 'cordon.N2'],
      ['voyant.b', [780, 340], [240, 340], 'cordon.N2'],
    ],
    scenarios: [
      { faults: { thermostat: 'ouvert' }, symptom: "« La bouilloire ne chauffe plus et le voyant reste éteint. »", lesson: "Le thermostat était bloqué ouvert. Indice : le voyant, branché APRÈS le thermostat, restait éteint alors que 230 V arrivaient jusqu'au thermostat." },
      { faults: { res: 'coupee' }, symptom: "« Le voyant s'allume mais l'eau reste froide. »", lesson: "La résistance était coupée. Le voyant, en parallèle, s'allumait quand même : c'est la preuve que la tension arrivait bien jusqu'à la résistance. À l'ohmmètre elle donnait ∞ au lieu de ≈ 26 Ω." },
      { faults: { voyant: 'grille' }, symptom: "« Elle chauffe normalement mais le voyant ne s'allume plus. »", lesson: "Seul le voyant était en panne. Comme il est en parallèle, il n'empêche pas le reste de fonctionner : une réparation à 2 €." },
      { faults: { thermostat: 'colle', thermofusible: 'grille' }, symptom: "« Elle a bouilli pendant très longtemps sans s'arrêter, puis plus rien. »", lesson: "Le thermostat avait ses contacts soudés : il ne coupait plus. La résistance a surchauffé et le fusible thermique a sacrifié le circuit. Remplacer seulement le fusible thermique aurait recommencé le cycle : il fallait aussi changer le thermostat." },
    ],
    tests: [
      { name: 'ON → la résistance chauffe, le voyant s\'allume, le thermostat coupe à 100 °C', controls: { sw: { on: true } }, expect: { res: 'on', voyant: 'on', thermostat: 'regule' } },
      { name: 'OFF → tout est arrêté', controls: { sw: { on: false } }, expect: { res: 'off', voyant: 'off' } },
    ],
  },

  /* ================================================================ */
  {
    id: 'sechecheveux',
    name: 'Sèche-cheveux',
    icon: '💇',
    difficulty: 3,
    intro: "Un commutateur à 3 positions à contacts cumulatifs : 0 = arrêt, 1 = air froid (sortie 1 : moteur), 2 = air chaud (sorties 1 et 2 : moteur + résistance). La résistance est protégée par un thermostat et un fusible thermique. Sans l'air du moteur, elle surchauffe !",
    ground: 'prise.N',
    ac: true,
    comps: [
      { id: 'prise', type: 'prise', x: 70, y: 230, params: { V: 230 }, state: { plugged: false } },
      { id: 'cordon', type: 'cordon', x: 200, y: 230, label: 'Cordon' },
      { id: 'com', type: 'commutateur', x: 370, y: 120, label: 'Commutateur', params: { cumul: true }, state: { pos: 0 } },
      { id: 'moteur', type: 'moteur', x: 560, y: 230, rot: 90, label: 'Moteur ventilateur', params: { P: 40, V: 230 } },
      { id: 'thermofusible', type: 'thermofusible', x: 700, y: 140, label: 'Fusible thermique', params: { T: 150, sensor: 'res' } },
      { id: 'thermostat', type: 'thermostat', x: 780, y: 200, rot: 90, label: 'Thermostat', params: { T: 90, sensor: 'res' } },
      { id: 'res', type: 'resistance', x: 780, y: 300, rot: 90, label: 'Résistance', params: { P: 1200, V: 230, cooledBy: 'moteur' } },
    ],
    wires: [
      ['prise.L', 'cordon.L1'], ['prise.N', 'cordon.N1'],
      ['cordon.L2', [240, 120], 'com.c'],
      ['com.p1', [560, 100], 'moteur.a'],
      ['com.p2', [660, 140], 'thermofusible.a'],
      ['thermofusible.b', [780, 140], 'thermostat.a'],
      ['thermostat.b', 'res.a'],
      ['res.b', [780, 380], [240, 380], 'cordon.N2'],
      ['moteur.b', [560, 380], [240, 380], 'cordon.N2'],
    ],
    scenarios: [
      { faults: { moteur: 'coupe', thermofusible: 'grille' }, symptom: "« Il chauffait sans souffler, ça sentait le chaud, et maintenant il est mort. »", lesson: "Le moteur avait un bobinage coupé. Sans air, la résistance a surchauffé et le fusible thermique a déclenché. Changer uniquement le fusible thermique l'aurait refait déclencher au test en position 2." },
      { faults: { res: 'coupee' }, symptom: "« Il ne souffle plus que de l'air froid, même en position 2. »", lesson: "La résistance chauffante était coupée (∞ à l'ohmmètre au lieu de ≈ 44 Ω). Le moteur, sur une autre branche, fonctionnait normalement." },
      { faults: { com: 'p2hs' }, symptom: "« La position 1 marche, mais en position 2 l'air reste froid. »", lesson: "Le contact de la sortie 2 du commutateur était usé : la résistance n'était jamais alimentée alors qu'elle était bonne (≈ 44 Ω) et que le fusible thermique était passant. Hors tension, on devait lire ∞ entre c et p2 en position 2." },
      { faults: { thermofusible: 'grille' }, symptom: "« Il ne se passe plus rien en position 2 sauf le moteur qui tourne. »", lesson: "Le fusible thermique avait déclenché avec l'âge. Il coupe uniquement la branche de la résistance, le moteur restait alimenté." },
      { faults: { cordon: 'coupeL' }, symptom: "« Il ne marche que si je tords le fil près de la fiche. »", lesson: "Conducteur coupé dans le cordon, panne classique à la sortie de la fiche." },
    ],
    tests: [
      { name: 'Position 0 → arrêt total', controls: { com: { pos: 0 } }, expect: { moteur: 'off', res: 'off' } },
      { name: 'Position 1 → moteur seul (air froid)', controls: { com: { pos: 1 } }, expect: { moteur: 'on', res: 'off' } },
      { name: 'Position 2 → moteur + résistance, thermostat régule', controls: { com: { pos: 2 } }, expect: { moteur: 'on', res: 'on', thermostat: 'regule' } },
    ],
  },

  /* ================================================================ */
  {
    id: 'ventilateur',
    name: 'Ventilateur de table',
    icon: '🌬️',
    difficulty: 3,
    intro: "Un moteur asynchrone à deux enroulements : le principal (P) est alimenté en direct, l'auxiliaire (A) à travers un condensateur qui lui permet de démarrer.",
    ground: 'prise.N',
    ac: true,
    comps: [
      { id: 'prise', type: 'prise', x: 70, y: 230, params: { V: 230 }, state: { plugged: false } },
      { id: 'cordon', type: 'cordon', x: 200, y: 230, label: 'Cordon' },
      { id: 'sw', type: 'interrupteur', x: 370, y: 120, label: 'Interrupteur', state: { on: false } },
      { id: 'moteur', type: 'moteur_async', x: 580, y: 230, label: 'Moteur', params: { P: 50, V: 230 } },
      { id: 'condo', type: 'condensateur', x: 700, y: 300, rot: 90, label: 'Condensateur', params: { C: 2 } },
    ],
    wires: [
      ['prise.L', 'cordon.L1'], ['prise.N', 'cordon.N1'],
      ['cordon.L2', [240, 120], 'sw.a'],
      ['sw.b', [540, 120], 'moteur.com'],
      ['moteur.P', [770, 210], [770, 380], [240, 380], 'cordon.N2'],
      ['moteur.A', [700, 250], 'condo.a'],
      ['condo.b', [700, 380], [240, 380], 'cordon.N2'],
    ],
    scenarios: [
      { faults: { condo: 'hs' }, symptom: "« Il ronronne mais l'hélice ne tourne pas. Si je la lance à la main, il démarre. »", lesson: "Le condensateur de démarrage était HS : l'enroulement auxiliaire n'était plus alimenté, le moteur ne pouvait plus démarrer seul. Panne n° 1 des ventilateurs !" },
      { faults: { moteur: 'coupeA' }, symptom: "« Il vibre un peu mais ne tourne pas. »", lesson: "L'enroulement auxiliaire du moteur était coupé (∞ entre com et A). Même symptôme qu'un condensateur HS : seul l'ohmmètre permet de trancher." },
      { faults: { moteur: 'coupeP' }, symptom: "« Il fait un léger bruit mais ne tourne pas. »", lesson: "L'enroulement principal était coupé (∞ entre com et P) : seul l'auxiliaire recevait du courant, insuffisant pour tourner." },
      { faults: { sw: 'ouvert' }, symptom: "« Rien ne se passe. »", lesson: "Interrupteur usé : ∞ en position ON." },
      { faults: { cordon: 'coupeN' }, symptom: "« Il s'est arrêté d'un coup. »", lesson: "Le neutre du cordon était coupé : le circuit n'était plus refermé." },
    ],
    tests: [
      { name: 'ON → le moteur tourne', controls: { sw: { on: true } }, expect: { moteur: 'on' } },
      { name: 'OFF → arrêt', controls: { sw: { on: false } }, expect: { moteur: 'off' } },
    ],
  },

  /* ================================================================ */
  {
    id: 'lampepoche',
    name: 'Lampe de poche (courant continu)',
    icon: '🔦',
    difficulty: 2,
    intro: "Passage au courant continu : une pile 4,5 V, un interrupteur, une résistance de limitation et une LED. Le multimètre passe en V= (DC).",
    ground: 'pile.M',
    ac: false,
    comps: [
      { id: 'pile', type: 'pile', x: 120, y: 230, label: 'Pile', params: { V: 4.5 }, state: { plugged: false } },
      { id: 'sw', type: 'interrupteur', x: 300, y: 120, label: 'Interrupteur', state: { on: false } },
      { id: 'cosse', type: 'connexion', x: 450, y: 120, label: 'Contact', params: { Rox: 400 } },
      { id: 'r', type: 'resistor', x: 600, y: 120, label: 'Résistance', params: { R: 100 } },
      { id: 'led', type: 'led', x: 720, y: 230, rot: 90, label: 'LED', params: { R: 100, Vn: 2.25 } },
    ],
    wires: [
      ['pile.P', [120, 120], 'sw.a'],
      ['sw.b', 'cosse.a'], ['cosse.b', 'r.a'],
      ['r.b', [720, 120], 'led.a'],
      ['led.b', [720, 340], [120, 340], 'pile.M'],
    ],
    scenarios: [
      { faults: { led: 'grillee' }, symptom: "« La lampe ne s'allume plus, pile neuve. »", lesson: "La LED était grillée : ∞ à l'ohmmètre. On mesurait toute la tension de la pile à ses bornes (4,5 V) sans qu'elle éclaire." },
      { faults: { pile: 'vide' }, symptom: "« Elle éclaire à peine. »", lesson: "La pile était usée : à vide elle donnait ≈ 2,7 V au lieu de 4,5 V, et sa résistance interne faisait encore chuter la tension sous charge." },
      { faults: { cosse: 'oxydee' }, symptom: "« Elle éclaire faiblement, pourtant la pile est neuve. »", lesson: "Un contact oxydé ajoutait ≈ 400 Ω dans le circuit. Indice décisif : une chute de tension de plusieurs volts aux bornes d'un simple contact, qui devrait faire 0 V." },
      { faults: { cosse: 'coupee' }, symptom: "« Plus rien ne s'allume. »", lesson: "Une cosse s'était débranchée : 4,5 V avant, 0 V après → circuit ouvert à cet endroit." },
      { faults: { sw: 'ouvert' }, symptom: "« Rien, même après avoir changé la pile et la LED. »", lesson: "L'interrupteur restait ouvert en position ON." },
    ],
    tests: [
      { name: 'ON → la LED éclaire normalement', controls: { sw: { on: true } }, expect: { led: 'on' } },
      { name: 'OFF → LED éteinte', controls: { sw: { on: false } }, expect: { led: 'off' } },
    ],
  },

  /* ================================================================ */
  {
    id: 'lavelinge',
    name: 'Lave-linge (simplifié)',
    icon: '🫧',
    difficulty: 4,
    view: [0, 0, 1020, 470],
    intro: "Un vrai petit réseau : fusible, sécurité de porte, un programmateur à 2 positions (1 = lavage : électrovanne + chauffe + moteur tambour ; 2 = vidange : pompe). Plusieurs branches en parallèle.",
    ground: 'prise.N',
    ac: true,
    fuse: { id: 'fusible', I: 16 },
    comps: [
      { id: 'prise', type: 'prise', x: 70, y: 230, params: { V: 230 }, state: { plugged: false } },
      { id: 'cordon', type: 'cordon', x: 200, y: 230, label: 'Cordon' },
      { id: 'fusible', type: 'fusible', x: 330, y: 120, label: 'Fusible', params: { I: 16 } },
      { id: 'porte', type: 'porte', x: 470, y: 120, label: 'Sécurité porte', state: { on: false } },
      { id: 'com', type: 'commutateur', x: 600, y: 120, label: 'Programmateur', state: { pos: 0 } },
      { id: 'ev', type: 'electrovanne', x: 730, y: 210, rot: 90, label: 'Électrovanne', params: { R: 4000 } },
      { id: 'thermostat', type: 'thermostat', x: 850, y: 190, rot: 90, label: 'Thermostat', params: { T: 60, sensor: 'res' } },
      { id: 'res', type: 'resistance', x: 850, y: 300, rot: 90, label: 'Résistance', params: { P: 2000, V: 230 } },
      { id: 'moteur', type: 'moteur', x: 960, y: 230, rot: 90, label: 'Moteur tambour', params: { P: 400, V: 230 } },
      { id: 'pompe', type: 'moteur', x: 590, y: 310, rot: 90, label: 'Pompe vidange', params: { P: 30, V: 230 } },
    ],
    wires: [
      ['prise.L', 'cordon.L1'], ['prise.N', 'cordon.N1'],
      ['cordon.L2', [240, 120], 'fusible.a'],
      ['fusible.b', 'porte.a'], ['porte.b', 'com.c'],
      ['com.p1', [730, 100], 'ev.a'],
      ['com.p1', [850, 100], 'thermostat.a'],
      ['thermostat.b', 'res.a'],
      ['com.p1', [960, 100], 'moteur.a'],
      ['com.p2', [660, 140], [660, 250], [590, 250], 'pompe.a'],
      ['ev.b', [730, 410], [240, 410], 'cordon.N2'],
      ['res.b', [850, 410], [240, 410], 'cordon.N2'],
      ['moteur.b', [960, 410], [240, 410], 'cordon.N2'],
      ['pompe.b', [590, 410], [240, 410], 'cordon.N2'],
    ],
    scenarios: [
      { faults: { res: 'cc', fusible: 'grille' }, symptom: "« Elle a disjoncté en plein cycle, maintenant plus rien ne s'allume. »", lesson: "La résistance était en court-circuit et a fait griller le fusible 16 A. Remplacer le fusible seul l'aurait refait sauter au test en position 1." },
      { faults: { porte: 'hs' }, symptom: "« Elle ne démarre plus, porte bien fermée. »", lesson: "Le micro-contact de sécurité de porte était cassé : 230 V avant lui, 0 V après. Tout le reste était en série derrière lui." },
      { faults: { pompe: 'bloque' }, symptom: "« Elle ne vidange plus, on entend un bourdonnement. »", lesson: "La pompe était bloquée par un corps étranger : électriquement correcte à l'ohmmètre, mais son rotor ne tournait pas. L'inspection visuelle était la clé." },
      { faults: { ev: 'coupee' }, symptom: "« Elle ne prend pas l'eau, mais le tambour tourne. »", lesson: "La bobine de l'électrovanne était coupée (∞ au lieu de ≈ 4 kΩ). Les autres branches en parallèle fonctionnaient." },
      { faults: { moteur: 'coupe' }, symptom: "« Elle prend l'eau et chauffe, mais le tambour ne bouge pas. »", lesson: "Le moteur du tambour avait un bobinage coupé : ∞ à l'ohmmètre." },
    ],
    tests: [
      { name: 'Porte ouverte, position 1 → rien ne fonctionne', controls: { porte: { on: false }, com: { pos: 1 } }, expect: { ev: 'off', res: 'off', moteur: 'off', pompe: 'off' } },
      { name: 'Porte fermée, position 1 (lavage) → eau + chauffe régulée + tambour', controls: { porte: { on: true }, com: { pos: 1 } }, expect: { ev: 'on', res: 'on', moteur: 'on', thermostat: 'regule', pompe: 'off' } },
      { name: 'Porte fermée, position 2 (vidange) → pompe seule', controls: { porte: { on: true }, com: { pos: 2 } }, expect: { pompe: 'on', ev: 'off', res: 'off', moteur: 'off' } },
    ],
  },
];
